"""Initial migration

Revision ID: 7d057845d615
Revises: 
Create Date: 2025-07-26 12:32:13.071768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d057845d615'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_login',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('login', sa.String(length=80), nullable=False),
    sa.Column('senha_hash', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_login', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_login_login'), ['login'], unique=True)

    op.create_table('user_bjj',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('data_atualizacao', sa.DateTime(), nullable=True),
    sa.Column('academia', sa.String(length=200), nullable=True),
    sa.Column('faixa', sa.String(length=50), nullable=True),
    sa.Column('graus', sa.Integer(), nullable=True),
    sa.Column('ultima_graduacao', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_login.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('user_dados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('data_atualizacao', sa.DateTime(), nullable=True),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('peso', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('nascimento', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.CheckConstraint('nascimento < CURRENT_DATE', name='check_nascimento_valido'),
    sa.CheckConstraint('peso > 0', name='check_peso_positivo'),
    sa.ForeignKeyConstraint(['user_id'], ['user_login.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    with op.batch_alter_table('user_dados', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_dados_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_dados_telefone'), ['telefone'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_dados', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_dados_telefone'))
        batch_op.drop_index(batch_op.f('ix_user_dados_email'))

    op.drop_table('user_dados')
    op.drop_table('user_bjj')
    with op.batch_alter_table('user_login', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_login_login'))

    op.drop_table('user_login')
    # ### end Alembic commands ###
