"""Primeira migrate, criando banco de usuarios

Revision ID: b69e6b95f2fb
Revises: 
Create Date: 2025-07-17 16:09:36.476540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b69e6b95f2fb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_cadastro', sa.DateTime(), nullable=True),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('login', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('senha_hash', sa.String(), nullable=True),
    sa.Column('academia', sa.String(), nullable=True),
    sa.Column('faixa', sa.String(), nullable=True),
    sa.Column('graus', sa.Integer(), nullable=False),
    sa.Column('peso_kg', sa.Float(), nullable=True),
    sa.Column('ultima_graduacao', sa.Date(), nullable=True),
    sa.Column('nascimento', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('login')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuario')
    # ### end Alembic commands ###
