"""melhorias_banco_dados

Revision ID: d7204d59f905
Revises: b69e6b95f2fb
Create Date: 2025-07-25 13:37:57.418495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7204d59f905'
down_revision = 'b69e6b95f2fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_dados', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_dados_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_dados_telefone'), ['telefone'], unique=False)

    with op.batch_alter_table('user_login', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_login_login'), ['login'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_login', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_login_login'))

    with op.batch_alter_table('user_dados', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_dados_telefone'))
        batch_op.drop_index(batch_op.f('ix_user_dados_email'))

    # ### end Alembic commands ###
